version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ibm
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: library
    env_file:
      - ./.env
    restart: always
    ports:
      - 3333:80
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
